const express = require('express')
const router = express.Router()
const categoryController = require('../controller/categoryController')
const { authenticate, authorizeAdmin } = require('../middleware/auth.middleware')
const { applySaleProgramToProducts } = require('../middleware/applySaleProgram.middleware')

router.get('/tree', categoryController.getCategoryTree)
router.get('/root-with-children', categoryController.getRootCategories)
router.get('/slug/:slug', categoryController.getCategoryBySlug)
router.get('/breadcrumb/:slug', categoryController.getCategoryWithBreadcrumb)
router.get('/:slug/hierarchy', categoryController.getCategoryHierarchy)
router.get('/search', categoryController.searchCategories)
router.get('/all-category', authenticate, categoryController.getCategories)
router.post('/add-category', authenticate, authorizeAdmin, categoryController.createCategory)
router.post('/', authenticate, authorizeAdmin, categoryController.createCategory)
router.put('/', authenticate, authorizeAdmin, categoryController.updateCategory)
router.put('/hierarchy', authenticate, authorizeAdmin, categoryController.updateCategoryHierarchy)
router.put('/:id/product-count', authenticate, authorizeAdmin, categoryController.updateProductCount)
router.put('/bulk-update-counts', authenticate, authorizeAdmin, categoryController.bulkUpdateProductCounts)
router.delete('/delete-category', authenticate, authorizeAdmin, categoryController.deleteCategory)
router.delete('/:id', authenticate, authorizeAdmin, categoryController.deleteCategory)
router.delete('/:id/force', authenticate, authorizeAdmin, categoryController.forceDeleteCategory)

module.exports = router
